name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@master

      - name: Setup Node
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Build dist
        run: npm run build

      - name: Deploy on firebase
      - uses: jakejarvis/firebase-deploy-action@master
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
